name: KRONOBAR
favicon: null
layout_spectrum: 0.6759348122868687
typography_spectrum: 0.4021594326477498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312f30'
    - '#ffffff'
    - '#adb8be'
    - '#0cafee'
    - '#d61f45'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
